### ISSUE TITLE
PESDK Ionic app crash on launch with no error.

### ISSUE THREAD

**Issue by Nitinchavda** [imgly/pesdk-ionic-demo#4]
I'm trying to use pesdk-ionic-demo but no luck from last 2 hours.
Ionic : -  CLI 4.10.1
Node : v8.10.0
Npm : 5.6.0
Mac Osx :  Mojave 10.14.2 (18C54)

Application crash on launch.

I'm using Trial version to check some of functionality work as expected before getting final licence. 

Many thanks in advance.
Nitin

**Comment by maltebaumann** [comment]
Hey Nitin,

You removed the original crash report and your mention of the missing submodule for some reason, but I'll reference them anyway:
- All 'logic' of this plugin is provided by the `pesdk-cordova-demo` submodule, so you need to fully clone and initialize it. The `publickey` error you mentioned hints at some git misconfiguration on your side
- If you're still experiencing a crash on launch, please use Xcode or Android Studio to receive the logs around the crash, otherwise I'm probably won't be able to help you

Thanks,
Malte

**Comment by Nitinchavda** [comment]
Hi Malte,

I got it working, i've copied license to but it doesn't copied in assets and crashed on launch.
